"""create observations and data_products

Revision ID: 0f6caa2f9bf7
Revises: 
Create Date: 2026-05-17 20:07:57.437231

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6caa2f9bf7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mast_obs_id', sa.String(length=64), nullable=False),
    sa.Column('program_id', sa.String(length=32), nullable=True),
    sa.Column('target_name', sa.String(length=256), nullable=True),
    sa.Column('instrument', sa.String(length=64), nullable=True),
    sa.Column('filters', sa.String(length=256), nullable=True),
    sa.Column('proposal_type', sa.String(length=64), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('observation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mast_obs_id', name='uq_observations_mast_obs_id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_instrument'), ['instrument'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_mast_obs_id'), ['mast_obs_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_target_name'), ['target_name'], unique=False)

    op.create_table('data_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('mast_product_id', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=True),
    sa.Column('file_extension', sa.String(length=16), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('calibration_version', sa.String(length=64), nullable=True),
    sa.Column('crds_context', sa.String(length=64), nullable=True),
    sa.Column('cloud_uri', sa.String(length=1024), nullable=True),
    sa.Column('mast_download_uri', sa.String(length=1024), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id', 'filename', name='uq_data_products_obs_filename')
    )
    with op.batch_alter_table('data_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_products_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_products_mast_product_id'), ['mast_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_products_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_products_product_type'), ['product_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_products_product_type'))
        batch_op.drop_index(batch_op.f('ix_data_products_observation_id'))
        batch_op.drop_index(batch_op.f('ix_data_products_mast_product_id'))
        batch_op.drop_index(batch_op.f('ix_data_products_filename'))

    op.drop_table('data_products')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_target_name'))
        batch_op.drop_index(batch_op.f('ix_observations_program_id'))
        batch_op.drop_index(batch_op.f('ix_observations_mast_obs_id'))
        batch_op.drop_index(batch_op.f('ix_observations_instrument'))

    op.drop_table('observations')
    # ### end Alembic commands ###
