"""phase 6 ai_report cost_estimate

Revision ID: 719f12cac17a
Revises: dff64aa9d87f
Create Date: 2026-06-02 00:33:31.907613

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719f12cac17a'
down_revision: str | Sequence[str] | None = 'dff64aa9d87f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_estimate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.drop_column('cost_estimate')

    # ### end Alembic commands ###
