"""phase 4: data_product_analyses

Revision ID: 7ed3b023ed62
Revises: c471d6cc58ae
Create Date: 2026-05-25 14:36:28.775286

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed3b023ed62'
down_revision: str | Sequence[str] | None = 'c471d6cc58ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_product_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_product_id', sa.Integer(), nullable=False),
    sa.Column('analyzer_name', sa.String(length=64), nullable=False),
    sa.Column('analyzer_version', sa.String(length=32), nullable=False),
    sa.Column('measurements_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('is_permanent_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id', 'analyzer_name', 'analyzer_version', name='uq_analyses_product_analyzer_version')
    )
    with op.batch_alter_table('data_product_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_product_analyses_data_product_id'), ['data_product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_product_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_product_analyses_data_product_id'))

    op.drop_table('data_product_analyses')
    # ### end Alembic commands ###
