"""add data_product_previews

Revision ID: c471d6cc58ae
Revises: 2d50cfb24ccd
Create Date: 2026-05-24 23:11:09.802362

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c471d6cc58ae'
down_revision: str | Sequence[str] | None = '2d50cfb24ccd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_product_previews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_product_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('storage_uri', sa.String(length=1024), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('is_permanent_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_product_id', 'variant', name='uq_previews_product_variant')
    )
    with op.batch_alter_table('data_product_previews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_product_previews_data_product_id'), ['data_product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_product_previews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_product_previews_data_product_id'))

    op.drop_table('data_product_previews')
    # ### end Alembic commands ###
